# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 11103 Structure Programming
tagline: Structured Programming (Spring 2026) @ PSUT
description: Lab resources, schedule, and assignments for Structure Programming 11103.
author: Essam Khader
baseurl: '/11103-Structure-Programming' # the subpath of your site, e.g. /blog
url: "https://essam-kh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.10.1
color_scheme: elegant_sunset
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Essam Khader:
    - '/11103-Structure-Programming/staff#essam-khader'
# footer_content: "This website was created using the <a href='https://github.com/kevinlin1/just-the-class'>Just the Class</a> template."

# Collections for website data
collections:
  staffers:
  modules:
    output: false



# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module


compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

sass:
  style: compressed

callouts: 
  warning: 
    title: Warning 
    color: red
  note:
    title: note
    color: yellow
  important:
    title: important
    color: blue
  tip:
    title: Tip 
    color: green
  example:
    title: Example 
    color: grey-dk

logo: "/assets/images/structure-logo.png"

enable_copy_code_button: false
math: katex

plugins:
  - jekyll-last-modified-at
footer_content: ""   # keep the default footer clean